"""Application-wide constants."""

# UI dimensions
SIDEBAR_WIDTH = 150
THUMBNAIL_WIDTH = 120
THUMBNAIL_HEIGHT = 160
THUMBNAIL_ITEM_WIDTH = 130
THUMBNAIL_ITEM_HEIGHT = 170
PREVIEW_MAX_WIDTH = 600
TOOLBAR_ICON_SIZE = 24
MIN_WINDOW_WIDTH = 1024
MIN_WINDOW_HEIGHT = 768

# PDF utils defaults
DEFAULT_THUMBNAIL_WIDTH = 150
DEFAULT_PREVIEW_WIDTH = 600

# Converter defaults
MARGIN_X = 50
MARGIN_Y_PT = 72  # 1 inch
LINE_HEIGHT_SMALL = 15
LINE_HEIGHT_NORMAL = 20
MAX_CHARS_PER_LINE = 80
FONT_NAME = "Helvetica"
FONT_SIZE_SMALL = 12
FONT_SIZE_NORMAL = 10

# Table margins
TABLE_MARGIN = 50
